# -*- coding: utf-8 -*-
"""SJF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-ShHk5yODe3dsIXGywC3l09-VHj58eu
"""

def bubble_sort(processes):
    n = len(processes)
    for i in range(n):
        for j in range(0, n-i-1):
            if processes[j][1] > processes[j+1][1]:
                processes[j], processes[j+1] = processes[j+1], processes[j]

def sjf_scheduling(processes):
    bubble_sort(processes)

    current_time = 0
    gantt_chart = []
    waiting_times = []

    for process_id, burst_time in processes:
        waiting_time = current_time
        waiting_times.append(waiting_time)

        gantt_chart.append(f'{current_time} {process_id}')

        current_time += burst_time

    gantt_chart.append(f'{current_time}')

    avg_waiting_time = sum(waiting_times) / len(processes)

    gantt_chart_str = " ".join(gantt_chart)

    return gantt_chart_str, avg_waiting_time


processes = [('p1', 21), ('p2', 3), ('p3', 6), ('p4', 2)]
gantt_chart, avg_wt = sjf_scheduling(processes)

print("Gantt Chart:", gantt_chart)
print(f"Average Waiting Time: {avg_wt:.2f}")